<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="My Store Project" duration-ms="56212" started-at="2022-02-10T16:36:59 IST" finished-at="2022-02-10T16:37:55 IST">
    <groups>
      <group name="Sanity">
        <method signature="LoginPageTest.LoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.mystore.testcases.LoginPageTest@2bbf4b8b]" name="LoginTest" class="com.mystore.testcases.LoginPageTest"/>
      </group> <!-- Sanity -->
      <group name="Smoke">
        <method signature="IndexPageTest.verifyTitle()[pri:0, instance:com.mystore.testcases.IndexPageTest@1563da5]" name="verifyTitle" class="com.mystore.testcases.IndexPageTest"/>
        <method signature="LoginPageTest.LoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.mystore.testcases.LoginPageTest@2bbf4b8b]" name="LoginTest" class="com.mystore.testcases.LoginPageTest"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="Index page tests" duration-ms="56212" started-at="2022-02-10T16:36:59 IST" finished-at="2022-02-10T16:37:55 IST">
      <class name="com.mystore.testcases.IndexPageTest">
        <test-method status="PASS" signature="loadConfig()[pri:0, instance:com.mystore.testcases.IndexPageTest@1563da5]" name="loadConfig" is-config="true" duration-ms="273" started-at="2022-02-10T16:36:59 IST" finished-at="2022-02-10T16:36:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.mystore.testcases.IndexPageTest@1563da5]" name="setup" is-config="true" duration-ms="17019" started-at="2022-02-10T16:36:59 IST" finished-at="2022-02-10T16:37:16 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyTitle()[pri:0, instance:com.mystore.testcases.IndexPageTest@1563da5]" name="verifyTitle" duration-ms="95" started-at="2022-02-10T16:37:16 IST" finished-at="2022-02-10T16:37:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.mystore.testcases.IndexPageTest@1563da5]" name="tearDown" is-config="true" duration-ms="831" started-at="2022-02-10T16:37:16 IST" finished-at="2022-02-10T16:37:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.mystore.testcases.IndexPageTest@1563da5]" name="afterSuite" is-config="true" duration-ms="748" started-at="2022-02-10T16:37:55 IST" finished-at="2022-02-10T16:37:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.mystore.testcases.IndexPageTest -->
      <class name="com.mystore.testcases.LoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.mystore.testcases.LoginPageTest@2bbf4b8b]" name="setup" is-config="true" duration-ms="12623" started-at="2022-02-10T16:37:18 IST" finished-at="2022-02-10T16:37:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="LoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.mystore.testcases.LoginPageTest@2bbf4b8b]" name="LoginTest" duration-ms="4497" started-at="2022-02-10T16:37:31 IST" data-provider="credentials" finished-at="2022-02-10T16:37:35 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[tusharnangre5446@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[8.380802646E9]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Unsuccessfull.. expected [My account - My Store] but found [Login - My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Unsuccessfull.. expected [My account - My Store] but found [Login - My Store]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.mystore.testcases.LoginPageTest.LoginTest(LoginPageTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.mystore.testcases.LoginPageTest@2bbf4b8b]" name="tearDown" is-config="true" duration-ms="933" started-at="2022-02-10T16:37:36 IST" finished-at="2022-02-10T16:37:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.mystore.testcases.LoginPageTest@2bbf4b8b]" name="setup" is-config="true" duration-ms="12767" started-at="2022-02-10T16:37:37 IST" finished-at="2022-02-10T16:37:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="LoginTest(java.lang.String, java.lang.String)[pri:0, instance:com.mystore.testcases.LoginPageTest@2bbf4b8b]" name="LoginTest" duration-ms="4458" started-at="2022-02-10T16:37:50 IST" data-provider="credentials" finished-at="2022-02-10T16:37:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[sandesh682@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123555.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Unsuccessfull.. expected [My account - My Store] but found [Login - My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Unsuccessfull.. expected [My account - My Store] but found [Login - My Store]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.mystore.testcases.LoginPageTest.LoginTest(LoginPageTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.mystore.testcases.LoginPageTest@2bbf4b8b]" name="tearDown" is-config="true" duration-ms="846" started-at="2022-02-10T16:37:54 IST" finished-at="2022-02-10T16:37:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.mystore.testcases.LoginPageTest -->
    </test> <!-- Index page tests -->
  </suite> <!-- My Store Project -->
</testng-results>
